<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Laptops_category_headphones</name>
   <tag></tag>
   <elementGuidId>e747cd08-5836-40f9-82e0-bb4a274c2ff6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='category_headphones']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;category_headphones&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb8fad2a-6c75-45f2-ba26-327913195f88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>category_headphones</value>
      <webElementGuid>73d5ad70-967b-457b-9afe-d77eadc5e741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>22b5aefb-a3fd-4a61-82ee-64d8ed75c1ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>cat.categoryValue</value>
      <webElementGuid>dc7e54b3-006c-43d4-af09-af1a80054bb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>96245d9e-5c28-40f3-9c4e-2f1d7c6655c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myAccountContainer&quot;)/div[@class=&quot;cube&quot;]/div[@class=&quot;categoriesBox&quot;]/div[@class=&quot;categoriesCheckboxes&quot;]/div[@class=&quot;option ng-scope&quot;]/input[@class=&quot;ng-pristine ng-untouched ng-valid&quot;]</value>
      <webElementGuid>9879d3f7-e02f-49a5-80c1-39365277fd5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='category_headphones']</value>
      <webElementGuid>2c5dfc13-ae2b-4069-9d08-546615964327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myAccountContainer']/div[5]/div[2]/div/div[4]/input</value>
      <webElementGuid>48ddc4a2-f52e-4ac1-94cf-076fa269ad4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>047acd01-72f8-4c98-a97d-5d9eb37008c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'category_headphones' and @type = 'checkbox']</value>
      <webElementGuid>ce299120-2c1c-45bc-b40c-ea14d59477aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
