<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CHECKOUT  (1,399.99)</name>
   <tag></tag>
   <elementGuidId>aa70de20-23bb-4a49-8f98-706c549183bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='checkOutPopUp']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkOutPopUp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b6369080-0ad4-4b8a-a05d-3d007d6f7de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkOutPopUp</value>
      <webElementGuid>d3f9267d-79d0-48e5-92d9-4cb08b374d3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>check_out_btn</value>
      <webElementGuid>a22f5efb-54ca-4dd5-ba2d-9d7a2b025efe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ccf708d7-faf4-48ec-b8df-08c06b3e8e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>roboto-medium ng-binding</value>
      <webElementGuid>b06dbe98-aaa7-4429-a343-ba62e68cbe01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>checkout($event)</value>
      <webElementGuid>770f9e41-4d67-4a57-855b-db0e17cfd036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CHECKOUT  ($1,399.99)</value>
      <webElementGuid>78e34de6-cd11-47db-9d89-e4ce4e9e5424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkOutPopUp&quot;)</value>
      <webElementGuid>f0ce39ef-e77f-4e3a-93a1-2a6b35c4ef8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='checkOutPopUp']</value>
      <webElementGuid>51b60a2f-e2bc-4011-ac88-c952d4d8ed23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tool-tip-cart[@id='toolTipCart']/div/table/tfoot/tr[2]/td/button</value>
      <webElementGuid>59d81d6a-1f19-4e1e-9c5f-0e4f0947d939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$1,399.99'])[2]/following::button[1]</value>
      <webElementGuid>c370cdef-b3f7-48a3-a370-1e0279b608c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(1 Item)'])[1]/following::button[1]</value>
      <webElementGuid>b691080a-5761-4b5c-9d91-e25c92ca09c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My account'])[2]/preceding::button[1]</value>
      <webElementGuid>2ecc09e3-cc40-4232-ac74-917e4ee9ab52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My orders'])[2]/preceding::button[1]</value>
      <webElementGuid>9926f65b-01d5-4387-acd8-5dec4e4b946c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/button</value>
      <webElementGuid>94628bea-03a7-40e7-b58d-d239335d5135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'checkOutPopUp' and @name = 'check_out_btn' and (text() = 'CHECKOUT  ($1,399.99)' or . = 'CHECKOUT  ($1,399.99)')]</value>
      <webElementGuid>25bf7117-ec18-4c54-b690-387a2af81698</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
