<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__safepay_username</name>
   <tag></tag>
   <elementGuidId>c00cbfe7-d2c0-4836-8f7d-8b16260115bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='safepay_username']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;safepay_username&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b9f42b46-def9-4563-9155-efd7ceb26c63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>safepay_username</value>
      <webElementGuid>cbc5742a-1952-4657-b165-2ed1f9c1269d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>48684f49-3f6a-45ae-8933-8dbc6cd386c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>secModel</value>
      <webElementGuid>a955276d-5fe2-4caf-b8b5-248c9f85e236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-scope in-focus</value>
      <webElementGuid>ea120585-c15a-4347-8b37-31f43900044b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paymentMethod&quot;)/div[1]/div[2]/sec-form[@class=&quot;ng-isolate-scope secForm&quot;]/sec-view[@class=&quot;ng-isolate-scope sec-view&quot;]/div[@class=&quot;inputContainer ng-scope&quot;]/input[@class=&quot;ng-pristine ng-untouched ng-valid ng-scope in-focus&quot;]</value>
      <webElementGuid>a5e60ebc-b814-4307-b461-9721d848a467</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='safepay_username']</value>
      <webElementGuid>9f2468c6-2e16-4a0f-acfb-aaab3721c9ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paymentMethod']/div/div[2]/sec-form/sec-view/div/input</value>
      <webElementGuid>6c6e2d97-dbed-4bd2-a43b-e7b7f95483bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/sec-form/sec-view/div/input</value>
      <webElementGuid>ba876edc-1f6a-4f74-bf49-f549477311ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'safepay_username' and @type = 'text']</value>
      <webElementGuid>ea7a3b89-cdbe-44b6-a35a-4c63caecc908</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
