<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_6690466631</name>
   <tag></tag>
   <elementGuidId>256c35db-b04f-4019-b16a-9cc3ac456db1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='orderNumberLabel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#orderNumberLabel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>9679909d-e0f6-4468-b48c-891b77623122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>orderNumberLabel</value>
      <webElementGuid>d3abeb42-dd08-4859-9d4a-a52f3a85629c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>a61b37ee-fea3-4480-85ec-a01260c26a59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>6690466631</value>
      <webElementGuid>3373a3f1-f078-4ff4-b63d-93499380f322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;orderNumberLabel&quot;)</value>
      <webElementGuid>ac037705-e500-4834-b1e8-105529ef2798</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='orderNumberLabel']</value>
      <webElementGuid>31159478-2b6e-40a4-b496-7df12984d0a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='orderPaymentSuccess']/p/label[2]</value>
      <webElementGuid>4544a6ec-a94b-41a5-ab33-c61ced58111c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[1]/following::label[1]</value>
      <webElementGuid>1b6a5c85-ef3f-429b-b519-eb91cca39e8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thank you for buying with Advantage'])[1]/following::label[2]</value>
      <webElementGuid>60d6bec0-2fcc-4aaa-9d4e-edda9e324c25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[2]/preceding::label[1]</value>
      <webElementGuid>d00e5936-b2cc-41e5-8c6d-9033048d97a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your warranty number is'])[1]/preceding::label[1]</value>
      <webElementGuid>57fafff1-a66b-4c5f-b9e8-a35f87f417b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='6690466631']/parent::*</value>
      <webElementGuid>67255e36-9709-461c-a9e3-4e147549b0fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/label[2]</value>
      <webElementGuid>fe998b21-99ac-4e7c-a706-37b4bda70a32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'orderNumberLabel' and (text() = '6690466631' or . = '6690466631')]</value>
      <webElementGuid>fc5b8631-30da-4239-afc9-3def6b5a0f2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
