<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Save changes in profile for future use</name>
   <tag></tag>
   <elementGuidId>73268c18-ea75-472d-b426-5cb65e2f84c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='paymentMethod']/div/div[2]/sec-form/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.roboto-light.ng-binding.ng-scope</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ac9f05f1-bbdd-4455-aad6-c05b9dce9160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>roboto-light ng-binding ng-scope</value>
      <webElementGuid>7773ba2f-8aaf-4a15-a631-6b4caa85e0ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>Save_changes_in_profile_for_future_use</value>
      <webElementGuid>6901bf27-3a39-4aea-b9e9-606b6963c039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save changes in profile for future use</value>
      <webElementGuid>06f8d908-0a58-4325-a163-249c3f47e779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paymentMethod&quot;)/div[1]/div[2]/sec-form[@class=&quot;ng-isolate-scope secForm&quot;]/div[@class=&quot;option marginTop&quot;]/span[@class=&quot;roboto-light ng-binding ng-scope&quot;]</value>
      <webElementGuid>c6f81f4a-e2e9-459d-9c5a-771791d63d21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paymentMethod']/div/div[2]/sec-form/div/span</value>
      <webElementGuid>ec25e418-dd09-4cff-814a-1bd71420bb97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- Including at least one number'])[1]/following::span[1]</value>
      <webElementGuid>dd0a1fbf-e6f2-43bc-8589-6e008316a98b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- Including at least one upper letter'])[1]/following::span[1]</value>
      <webElementGuid>b3ba566e-a705-4347-95c3-07a555100c28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to shipping details'])[1]/preceding::span[1]</value>
      <webElementGuid>3f7321a5-8b86-419e-bbd5-26f473fe7728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAY NOW'])[1]/preceding::span[1]</value>
      <webElementGuid>43ce4c78-f22e-4e32-91ba-1978a1cb8236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/sec-form/div/span</value>
      <webElementGuid>8b68d0a5-a791-449a-9d87-cdf5b6939a64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Save changes in profile for future use' or . = 'Save changes in profile for future use')]</value>
      <webElementGuid>e7799a3d-eabf-4d2d-bbda-c01f2e1a738d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
