<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_View Details_popular_item_21_img</name>
   <tag></tag>
   <elementGuidId>5c8f11d8-c89f-4350-8c30-ad3da58b81f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@name='popular_item_21_img']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[name=&quot;popular_item_21_img&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1ad83cea-a54b-450d-baaa-58498619397f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>popular_item_21_img</value>
      <webElementGuid>21f75d2d-4c82-406e-a079-2bfeed8edb6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-src</name>
      <type>Main</type>
      <value>css/images/Popular-item1.jpg</value>
      <webElementGuid>9ee25496-1fed-479c-924a-fed81ec40281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Special-offer</value>
      <webElementGuid>356920d8-779a-4b21-afdd-83ab9370494f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>75635fd5-a36d-412d-89fb-1fb11b6069ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>881046f6-cf1b-4f7d-97e6-60dad4d5a3c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>css/images/Popular-item1.jpg</value>
      <webElementGuid>4ee92480-f816-4f8f-b63d-32b865d860a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popular_items&quot;)/div[@class=&quot;grid-table center&quot;]/div[@class=&quot;ng-scope&quot;]/figure[1]/img[1]</value>
      <webElementGuid>c048ddca-bffd-4e16-bcbc-a6456a9a276d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@name='popular_item_21_img']</value>
      <webElementGuid>1570f30c-8a5d-4fee-b86a-068f66918337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='popular_items']/div/div[3]/figure/img</value>
      <webElementGuid>45cb9013-7df7-41d2-8cc0-d8b5b6e74aca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Special-offer'])[4]</value>
      <webElementGuid>c5630980-6c7f-472f-a50c-21e7ba4308e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/figure/img</value>
      <webElementGuid>cfa2680d-015d-4f56-8160-308c2f5c36ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@name = 'popular_item_21_img' and @alt = 'Special-offer' and @href = 'javascript:void(0)' and @src = 'css/images/Popular-item1.jpg']</value>
      <webElementGuid>b0e0eda4-16cb-41e4-9ddf-9c247fb98cd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
