<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CHECKOUT  (0.00)_hrefUserIcon</name>
   <tag></tag>
   <elementGuidId>c55751ab-96bb-4884-8d98-c739789b648c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hrefUserIcon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='hrefUserIcon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8709a1ab-a572-4522-a1de-a65ec5bb238f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hrefUserIcon</value>
      <webElementGuid>1f49d312-9753-4de5-b0bb-77ab99b15744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>USER</value>
      <webElementGuid>430c3861-97c0-43a1-8085-29e86c41aa10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hrefUserIcon&quot;)</value>
      <webElementGuid>498a4d11-8aa8-4e66-8626-8cafdd166de4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='hrefUserIcon']</value>
      <webElementGuid>1f5ac761-076b-4ffd-b3c5-9896dd61bc60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='menuUserLink']/a</value>
      <webElementGuid>3b19f8bc-e342-436f-bdf2-6a1a2a1ae360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$0.00'])[1]/following::a[2]</value>
      <webElementGuid>7612045f-88f5-43c1-8f4e-fa92279672a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My account'])[2]/preceding::a[1]</value>
      <webElementGuid>24495de2-3673-4a0c-afbc-9bf95cfb3d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My orders'])[2]/preceding::a[1]</value>
      <webElementGuid>6218be21-5d43-4997-a075-aaffd62b0c11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[3]/a/a</value>
      <webElementGuid>0c3f6898-b028-401c-9951-84e01e90f877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'hrefUserIcon' and @title = 'USER']</value>
      <webElementGuid>5406204f-617e-43cf-b8dd-3c9a16c2060a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
