<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_PAY NOW</name>
   <tag></tag>
   <elementGuidId>2a55e0d3-b90a-4abb-8491-ec8c1eb9987a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='pay_now_btn_SAFEPAY']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pay_now_btn_SAFEPAY</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>836db2d3-7d6f-4b68-aa47-b180332a29e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pay_now_btn_SAFEPAY</value>
      <webElementGuid>cd3f30c7-5792-48e6-86de-41e3e9440388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>746ff965-da93-4ac6-91fb-b0a5b15f391d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sec-sender-a ng-scope</value>
      <webElementGuid>6c9d8b97-7459-4362-9fd4-5ff517d22007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9b6bdc2d-5ac4-445d-ac6e-f3b504ddfba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>senderCtrl.send()</value>
      <webElementGuid>fea18393-636c-4529-a79f-bf40c2005602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PAY NOW</value>
      <webElementGuid>f281d0e2-f8ff-4e35-bf16-a51cd25a1dee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pay_now_btn_SAFEPAY&quot;)</value>
      <webElementGuid>ce61f619-6e4e-4fe1-a424-df5e9030bbcb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='pay_now_btn_SAFEPAY']</value>
      <webElementGuid>e5e3315e-7794-4d6e-8b4b-aad1d9334e55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//sec-sender[@id='payNowSPDrtv']/button</value>
      <webElementGuid>f5a03d0b-4976-4148-bc78-70c69356fe72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to shipping details'])[1]/following::button[1]</value>
      <webElementGuid>8e5caa3c-9818-4691-bee2-5f160363bcd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save changes in profile for future use'])[2]/following::button[1]</value>
      <webElementGuid>0d8c4669-14e6-4c23-bf19-8e284caa9207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MasterCredit'])[1]/preceding::button[1]</value>
      <webElementGuid>d23c94fe-f3eb-462d-b6e1-7d7987b268d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/preceding::button[1]</value>
      <webElementGuid>24c168f6-66ac-4dfa-a441-c151b749617c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PAY NOW']/parent::*</value>
      <webElementGuid>221a7e18-988d-434f-966a-018e07f9056d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/sec-sender/button</value>
      <webElementGuid>77203027-326b-4d6a-ad66-f22f79ce505a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'pay_now_btn_SAFEPAY' and @type = 'button' and (text() = 'PAY NOW' or . = 'PAY NOW')]</value>
      <webElementGuid>02443681-b9eb-461e-9a1f-4b2650cfc637</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
