<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Shop Now</name>
   <tag></tag>
   <elementGuidId>fbf35a3f-fca5-41b3-a041-f7a5e0980253</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='miceLink']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#miceLink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>257b7006-3534-4aa3-b62a-02c1e383f8d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>miceLink</value>
      <webElementGuid>efed3aba-76d4-4279-8245-25e2227fde93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shop_nowSub roboto-regular ng-scope</value>
      <webElementGuid>3e3c6255-0217-4e11-a04c-c4503b773df0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>Shop_Now</value>
      <webElementGuid>348f4c51-74ae-4178-be39-f6e2d5d7d66d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shop Now</value>
      <webElementGuid>7e224846-e59e-4413-8c15-1dda92a7963e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;miceLink&quot;)</value>
      <webElementGuid>cba69e3a-a6cb-46fe-a2a1-676e05cfb46a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='miceLink']</value>
      <webElementGuid>5fb5fb37-e86c-4221-90ee-25f324172b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='miceImg']/div/label</value>
      <webElementGuid>a9095a7d-9e22-4fcd-811c-511b0748e0f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MICE'])[1]/following::label[1]</value>
      <webElementGuid>d7b99cf0-d90d-400a-b2a4-21ad91bcbbbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop Now'])[3]/following::label[1]</value>
      <webElementGuid>a2f84433-efc8-47ea-9b06-c09992600224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HEADPHONES'])[1]/preceding::label[1]</value>
      <webElementGuid>81cc897d-dd4f-45e6-9df3-9616b927a2d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop Now'])[5]/preceding::label[1]</value>
      <webElementGuid>93a2309a-fe00-4215-8a36-db536421bc3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/label</value>
      <webElementGuid>7426b423-40e5-4619-b824-ca0d428fc2d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'miceLink' and (text() = 'Shop Now' or . = 'Shop Now')]</value>
      <webElementGuid>3922427c-d57d-407f-8426-3fe6c5805f79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
