<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>1dc27071-6db8-4687-9aa7-ef0d29419f2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='output']/div/div[2]/a[3]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>89b0814a-be27-414d-949b-90a5635d8ece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-src</name>
      <type>Main</type>
      <value>/catalog/fetchImage?image_id=2100</value>
      <webElementGuid>9e910ec2-d4de-4275-a6a7-db0488b933af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/catalog/fetchImage?image_id=2100</value>
      <webElementGuid>524bebab-829f-4004-bb4b-6cae396b1082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;output&quot;)/div[@class=&quot;searchPopUp&quot;]/div[@class=&quot;top6Products&quot;]/a[@class=&quot;product ng-scope&quot;]/img[1]</value>
      <webElementGuid>806b6fb6-37c1-4c1b-af81-14247dded6ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='output']/div/div[2]/a[3]/img</value>
      <webElementGuid>e74c64f9-97a5-45ee-8963-4496b29de8a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/img</value>
      <webElementGuid>1ad0ee1f-dce4-4e96-95cc-203b67f2fd82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/catalog/fetchImage?image_id=2100']</value>
      <webElementGuid>4ba6e557-be0f-4b50-85fe-22adafbb4614</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
